version: "3"

includes:
  prerequisities: ./Taskfile_{{OS}}.yml

tasks:
  help:
    silent: true
    cmds:
      - echo "Usage task [task] [options]"
      - echo "Targets:"
      - echo "  install  - Install npm and its dependencies"
      - echo "  build    - Build the app using npm"
      - echo "  run      - Run the Python app"
      - echo "  clean    - Clean all Node.js files and remove the 'web' directory"
      - echo "  binaries - Build the binaries using pyinstaller"

  run:
    deps: ["install", "build"]
    cmds:
      - python src

  install:
    cmds:
      - cd src/web-src && npm i
      - cd src && pip3 install -r requirements.txt
    sources:
      - src/web-src/package-lock.json
      - src/web-src/package.json
      - src/requirements.txt
    generates:
      - src/web-src/node_modules
      - src/web-src/package-lock.json
      - src/web-src/package.json

  build:
    deps:
      - task: install
      - task: prerequisities:build
    sources:
      - src/web-src/
    generates:
      - src/web
      - src/web/index.html

  clean:
    deps: ["prerequisities:clean"]

  binaries:
    deps: ["install", "build"]
    cmds:
      - pip install -r requirements.txt
      - cd src && python -m eel app.py web --onefile --name=TCPChat --distpath=../dist --workpath=../build

  .phony:
    - install
    - run
    - clean
    - help
