version: "3"

includes:
  prerequisities: ./Taskfile_{{OS}}.yml

tasks:
  all:
    deps: ["install", "build", "run"]

  help:
    silent: true
    cmds:
      - echo "Usage task [task] [options]"
      - echo "Targets:"
      - echo "  install  - Install npm and its dependencies"
      - echo "  build    - Build the app using npm"
      - echo "  run      - Run the Python app"
      - echo "  clean    - Clean all Node.js files and remove the 'web' directory"
      - echo "  binaries - Build the binaries using pyinstaller"

  run:
    cmds:
      - python src

  install:
    cmds:
      - cd src/web-src && npm ci
      - cd src && pip3 install -r requirements.txt

  build:
    deps: ["install", "prerequisities:build"]

  clean:
    deps: ["prerequisities:clean"]

  binaries:
    deps: ["install", "build"]
    cmds:
      - pip install -r requirements.txt
      - cd src && python -m eel app.py web --onefile --name=TCPChat --distpath=../dist --workpath=../build

  .phony:
    - install
    - build
    - run
    - clean
    - help
