name: Server CI

on:
  push:
    branches:
      - feature/server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libssl-dev
        openssl version
        find /usr/lib -name libssl.so.3
        

    - name: Build Server
      run: |
        cd server
        make