name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc
        sudo apt-get install g++
        sudo apt-get install libssl-dev
        sudo apt-get install cmake
        sudo apt-get install make
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo apt-get install sqlite3
        sudo apt-get install libsqlite3-dev

    - name: Build tests
      run: |
            cd server/test
            cmake .
            make

    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
          name: test_artifacts
          path: server/test/*.test
  
  account_controller_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download test artifacts
      uses: actions/download-artifact@v2
      with:
        name: test_artifacts
        path: server/test

    - name: Run account_controller_tests
      run: |
        cd server/test
        chmod +x account_controller_tests.test
        ./account_controller_tests.test

  friend_list_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v2
      with:
        name: test_artifacts
        path: server/test


    - name: Run friend_list_tests
      run: |
        pwd
        cd server/test
        chmod +x friend_list_tests.test
        ./friend_list_tests.test

  rsa_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v2
      with:
        name: test_artifacts
        path: server/test

    - name: Run rsa_tests
      run: |
        cd server/test
        chmod +x rsa_tests.test
        ./rsa_tests.test