name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libssl-dev libsqlite3-dev

    - name: Install Google Test
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make

    - name: Build tests
      run: |
        cd server/test
        cmake .
        make

    - name: Upload test binaries
      uses: actions/upload-artifact@v2
      with:
        name: test-binaries
        path: server/test/*.test

  account_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download test binaries
      uses: actions/download-artifact@v2
      with:
        name: test-binaries
        path: server/test

    - name: Run Account tests
      run: |
        cd server/test
        ./account_controller_tests.test

  friendlist_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download test binaries
      uses: actions/download-artifact@v2
      with:
        name: test-binaries
        path: server/test

    - name: Run Friendlist tests
      run: |
        cd server/test
        ./friendlist_controller_tests.test